const crypto = require('crypto');
const { compress, decompress } = require('./utils/compression');
const { derivePayloadKey } = require('./utils/keyDerivation');
const { encrypt, decrypt } = require('./utils/encryption');
const { verifyHash, macHash, verifyMacHash } = require('./utils/hashing');
const { encryptFile, decryptFile } = require('./utils/streamCrypto');
const { encryptMany, decryptMany, encryptManyParallel, decryptManyParallel } = require('./utils/batchOperations');
const {
  createTimeHeader,
  createPayloadBody,
  buildPayload,
  decodePayload,
  parsePayload,
  validateFreshness,
  validateLegacyPolicy
} = require('./utils/payload');
const { PAYLOAD_VERSION_V3, PAYLOAD_VERSION_V4, SALT_SIZE, ARGON2_SALT_SIZE, MAX_PLAINTEXT_SIZE } = require('./constants');

const normalizeOptions = (options) => {
  if (options === undefined || options === null) {
    return {};
  }

  if (typeof options !== 'object' || Array.isArray(options)) {
    throw new TypeError('options must be an object');
  }

  return options;
};

const normalizeCompressionLevel = (value) => {
  if (!Number.isInteger(value) || value < 0 || value > 9) {
    throw new RangeError('compressionLevel must be an integer between 0 and 9');
  }

  return value;
};

const normalizeProgressHandler = (value) => {
  if (value === undefined || value === null) {
    return null;
  }

  if (typeof value !== 'function') {
    throw new TypeError('onProgress must be a function');
  }

  return value;
};

const resolveHashAuthKey = (payload, secretKey) => {
  if (payload.version === PAYLOAD_VERSION_V3) {
    return secretKey;
  }

  return null;
};

const hasKeyedMacIntegrity = (payload) => payload.version >= PAYLOAD_VERSION_V4;

const normalizeDecryptedOutput = (payload, data) => {
  if (payload.timeMetadata?.isBinary) {
    return Buffer.from(data);
  }

  return data.toString('utf8');
};

const restorePlaintext = async (payload, decrypted) => {
  if (payload.timeMetadata?.isCompressed === false) {
    return decrypted;
  }

  return decompress(decrypted);
};

class K9crypt {
  constructor(secretKey, options = {}) {
    options = normalizeOptions(options);

    if (secretKey === undefined || secretKey === null) {
      this.secretKey = crypto.randomBytes(50);
      this._autoGenerated = true;
    }

    if (secretKey !== undefined && secretKey !== null) {
      if (typeof secretKey !== 'string' && !Buffer.isBuffer(secretKey)) {
        throw new TypeError('secretKey must be a string or Buffer');
      }

      if (typeof secretKey === 'string' && secretKey.length === 0) {
        throw new TypeError('secretKey must not be empty');
      }

      if (Buffer.isBuffer(secretKey) && secretKey.length === 0) {
        throw new TypeError('secretKey must not be empty');
      }

      this._autoGenerated = false;
      this.secretKey = Buffer.isBuffer(secretKey) ? Buffer.from(secretKey) : secretKey;
    }

    const level = normalizeCompressionLevel(options.compressionLevel ?? 0);

    this.defaultCompressionLevel = level;
  }

  getGenerated() {
    return this._autoGenerated ? Buffer.from(this.secretKey) : null;
  }

  async encrypt(plaintext, options = {}) {
    try {
      options = normalizeOptions(options);

      const inputBuf = Buffer.isBuffer(plaintext) ? plaintext : Buffer.from(plaintext, 'utf8');
      if (inputBuf.length > MAX_PLAINTEXT_SIZE) {
        throw new Error('Payload too large');
      }
      const compressionLevel = normalizeCompressionLevel(options.compressionLevel ?? this.defaultCompressionLevel);
      const shouldCompress = compressionLevel > 0;
      const timePayload = createTimeHeader({ ...options, isBinary: Buffer.isBuffer(plaintext), isCompressed: shouldCompress });
      const encryptedInput = shouldCompress ? await compress(inputBuf, compressionLevel, !timePayload.timeMetadata.isBinary) : inputBuf;
      const salt = crypto.randomBytes(SALT_SIZE);
      let key = null;

      try {
        key = await derivePayloadKey(this.secretKey, salt, timePayload.timeMetadata);
        const { iv1, iv2, iv3, iv4, iv5, encrypted, tag1 } = await encrypt(encryptedInput, key, timePayload.header);
        const body = createPayloadBody({
          header: timePayload.header,
          salt,
          iv1,
          iv2,
          iv3,
          iv4,
          iv5,
          encrypted,
          tag1
        });
        const integritySalt = crypto.randomBytes(ARGON2_SALT_SIZE);
        const dataHash = await macHash(body, integritySalt, key);

        return buildPayload(body, integritySalt, dataHash);
      } finally {
        if (key) {
          key.fill(0);
        }
      }
    } catch (error) {
      throw new Error('Encryption failed');
    }
  }

  async decrypt(ciphertext, options = {}) {
    try {
      options = normalizeOptions(options);

      const data = decodePayload(ciphertext);
      const payload = parsePayload(data);
      validateLegacyPolicy(payload, options);
      const useKeyedMacIntegrity = hasKeyedMacIntegrity(payload);

      if (!useKeyedMacIntegrity) {
        const hashAuthKey = resolveHashAuthKey(payload, this.secretKey);

        if (!(await verifyHash(payload.body, payload.dataHash, payload.argon2Salt, hashAuthKey))) {
          throw new Error('Data integrity check failed');
        }
      }

      validateFreshness(payload, options);

      let key = null;
      let decrypted = null;

      try {
        key = await derivePayloadKey(this.secretKey, payload.salt, payload.timeMetadata);
        if (useKeyedMacIntegrity && !(await verifyMacHash(payload.body, payload.dataHash, payload.argon2Salt, key))) {
          throw new Error('Data integrity check failed');
        }

        decrypted = await decrypt(
          payload.encrypted,
          key,
          payload.iv1,
          payload.iv2,
          payload.iv3,
          payload.iv4,
          payload.iv5,
          payload.tag1,
          payload.header
        );
      } finally {
        if (key) {
          key.fill(0);
        }
      }

      const decompressed = await restorePlaintext(payload, decrypted);
      if (decompressed.length > MAX_PLAINTEXT_SIZE) {
        throw new Error('Payload too large');
      }

      return normalizeDecryptedOutput(payload, decompressed);
    } catch (error) {
      throw new Error('Decryption failed');
    }
  }

  async encryptFile(plaintext, options = {}) {
    try {
      options = normalizeOptions(options);

      const compressionLevel = normalizeCompressionLevel(options.compressionLevel ?? this.defaultCompressionLevel);
      const onProgress = normalizeProgressHandler(options.onProgress);

      return await encryptFile(plaintext, this.secretKey, {
        compressionLevel,
        onProgress,
        timeStepSeconds: options.timeStepSeconds,
        stepSeconds: options.stepSeconds,
        issuedAt: options.issuedAt,
        issuedAtUnix: options.issuedAtUnix
      });
    } catch (error) {
      throw new Error('File encryption failed');
    }
  }

  async decryptFile(ciphertext, options = {}) {
    try {
      options = normalizeOptions(options);

      const onProgress = normalizeProgressHandler(options.onProgress);

      return await decryptFile(ciphertext, this.secretKey, {
        onProgress,
        allowLegacyPayloads: options.allowLegacyPayloads,
        maxAgeSeconds: options.maxAgeSeconds,
        allowedClockSkewSeconds: options.allowedClockSkewSeconds,
        nowUnixSeconds: options.nowUnixSeconds
      });
    } catch (error) {
      throw new Error('File decryption failed');
    }
  }

  async encryptMany(dataArray, options = {}) {
    try {
      options = normalizeOptions(options);

      const compressionLevel = normalizeCompressionLevel(options.compressionLevel ?? this.defaultCompressionLevel);
      const onProgress = normalizeProgressHandler(options.onProgress);
      const parallel = options.parallel || false;

      if (parallel) {
        return await encryptManyParallel(dataArray, this.secretKey, {
          compressionLevel,
          batchSize: options.batchSize,
          timeStepSeconds: options.timeStepSeconds,
          stepSeconds: options.stepSeconds,
          issuedAt: options.issuedAt,
          issuedAtUnix: options.issuedAtUnix
        });
      }

      return await encryptMany(dataArray, this.secretKey, {
        compressionLevel,
        onProgress,
        timeStepSeconds: options.timeStepSeconds,
        stepSeconds: options.stepSeconds,
        issuedAt: options.issuedAt,
        issuedAtUnix: options.issuedAtUnix
      });
    } catch (error) {
      throw new Error('Multiple encryption failed');
    }
  }

  async decryptMany(ciphertextArray, options = {}) {
    try {
      options = normalizeOptions(options);

      const onProgress = normalizeProgressHandler(options.onProgress);
      const skipInvalid = options.skipInvalid || false;
      const parallel = options.parallel || false;

      if (parallel) {
        return await decryptManyParallel(ciphertextArray, this.secretKey, {
          skipInvalid,
          batchSize: options.batchSize,
          allowLegacyPayloads: options.allowLegacyPayloads,
          maxAgeSeconds: options.maxAgeSeconds,
          allowedClockSkewSeconds: options.allowedClockSkewSeconds,
          nowUnixSeconds: options.nowUnixSeconds
        });
      }

      return await decryptMany(ciphertextArray, this.secretKey, {
        skipInvalid,
        onProgress,
        allowLegacyPayloads: options.allowLegacyPayloads,
        maxAgeSeconds: options.maxAgeSeconds,
        allowedClockSkewSeconds: options.allowedClockSkewSeconds,
        nowUnixSeconds: options.nowUnixSeconds
      });
    } catch (error) {
      throw new Error('Multiple decryption failed');
    }
  }
}

module.exports = K9crypt;
